language: node_js
node_js:
  - 0.12

# Make sure we have new NPM.
before_install:
  - npm install -g codeclimate-test-reporter
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g bower
  - 'bower install'

after_script:
  - 'mv ./client/coverage/**/lcov.info ./client/ '
  - 'ls ./client'
  - 'cd client'
  - 'codeclimate < ./lcov.info'
